### PR TITLE
Migrate to GitHub Actions, support Ruby 3.0 and support Rails 6.1

### PR DESCRIPTION
**Pull request by qnighy**
## Why

- We want to use the library with Ruby 3.0 / Rails 6.1.
- Travis now imposes a relatively tight limit on OSS projects and it sometimes fails due to credit shortage.

## What

- Migrated from Travis CI to GitHub Actions.
  - It's not run in ngtk/open_api until it's merged, here's the result on my side: https://github.com/qnighy/open_api/actions/runs/1077009889
- Supported Ruby 3.0 by fixing keyword parameters.
  - Turned `def initialize(**hash)` into `def initialize(hash)`
  - We could instead fix the tests to remove syntax like `OpenApi::Paths.new({ ... })` but I thought it's the intended use.
- Relaxed the version constraint on Rails.
  - Also configured the CI to test in various versions of Rails.

### CODE REVIEW

**Review by ngtk — APPROVED** [review]
> Migrated from Travis CI to GitHub Actions.

Thank you so much.

> * We could instead fix the tests to remove syntax like `OpenApi::Paths.new({ ... })` but I thought it's the intended use.

There is no special reason for that, but it's intended.

**Comment by ngtk** [comment]
I'm going to release the next version soon. please wait a moment.

**Comment by qnighy** [comment]
Thanks for the quick action!

Looks like the action is stalling? How about rerunning it, as no jobs there have side effects?

screenshot

**Comment by ngtk** [comment]
> Looks like the action is stalling? How about rerunning it, as no jobs there have side effects?

Oh, I missed it 🙈 I reran it and it was passed.

Also I already have pushed the gem to rubygems. https://rubygems.org/gems/open_api/versions/0.6.0

Thank you for your contributing! 🎉

**Pull request merged**
